version: '3.5'

networks:
  polygon:
    external: true

configs:
  prover_db_init_sql:
    file: ./test/config/prover/initproverdb.sql
  test_keystore_sequencer:
    file: ./test/test.keystore.sequencer
  test_keystore_aggregator:
    file: ./test/test.keystore.aggregator
  config_zkevm_node_toml:
    file: ./test/config/node/config.zkevm.node.toml
  genesis_local_json:
    file: ./test/config/node/genesis.local.json
  test_keystore_claimtx:
    file: ./test/test.keystore.claimtx
  config_local_toml:
    file: ./config/config.local.toml
  config_prover_json:
    file: ./test/config/prover/config.prover.json

services:
  zkevm-state-db:
    image: postgres
    networks:
      - polygon
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
      placement:
        constraints:
        - node.hostname==hzhx-System-Product-Name
    configs:
      - source: prover_db_init_sql
        target: /docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=state_user
      - POSTGRES_PASSWORD=state_password
      - POSTGRES_DB=state_db
    command: ["postgres", "-N", "500"]

  zkevm-pool-db:
    image: postgres
    networks:
      - polygon
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
      placement:
        constraints:
        - node.hostname==hzhx-System-Product-Name
    environment:
      - POSTGRES_USER=pool_user
      - POSTGRES_PASSWORD=pool_password
      - POSTGRES_DB=pool_db
    command: ["postgres", "-N", "500"]

  zkevm-bridge-db:
    image: postgres
    networks:
      - polygon
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
      placement:
        constraints:
        - node.hostname==hzhx-System-Product-Name
    # expose:
    #   - 5435
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_db
    command: ["postgres", "-N", "500"]

  zkevm-node:
    image: hermeznetwork/zkevm-node:v0.5.0-RC18
    networks:
      - polygon
    deploy:
      placement:
        constraints:
        - node.hostname==hzhx-System-Product-Name
    ports:
      - 8123:8123
      - 61090:61090
    environment:
      - ZKEVM_NODE_STATE_DB_HOST=bridge1_zkevm-state-db
      - ZKEVM_NODE_POOL_HOST=bridge1_zkevm-pool-db
      - ZKEVM_NODE_RPC_DB_HOST=bridge1_zkevm-rpc-db
    configs:
      - source: test_keystore_sequencer
        target: /pk/keystore.sequencer
      - source: test_keystore_aggregator
        target: /pk/keystore.aggregator
      - source: config_zkevm_node_toml
        target: /app/config.toml
      - source: genesis_local_json
        target: /app/genesis.json
    command: 
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node approve --network custom --custom-network-file /app/genesis.json --am 115792089237316195423570985008687907853269984665640564039457584007913129639935 -y --cfg /app/config.toml --key-store-path /pk/keystore.sequencer --password testonly &&
         /app/zkevm-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components \"synchronizer,rpc,sequencer,sequence-sender,aggregator,eth-tx-manager,l2gaspricer\" --http.api eth,net,debug,zkevm,txpool,web3"

  zkevm-mock-l1-network:
    image: hermeznetwork/geth-zkevm-contracts:v2.1.1-fork.7-geth1.12.0
    networks:
      - polygon
    deploy:
      placement:
        constraints:
        - node.hostname==hzhx-System-Product-Name
    ports:
      - 8545:8545
      - 8546:8546

  zkevm-prover:
    image: hermeznetwork/zkevm-prover:v4.0.0-RC27
    networks:
      - polygon
    deploy:
      placement:
        constraints:
        - node.hostname==hzhx-System-Product-Name
    ports:
      - 50051:50051 # Prover
      - 50052:50052 # MockProver
      - 50061:50061 # MT
      - 50071:50071 # Executor
    configs:
      - source: config_prover_json
        target: /usr/src/app/config.json
    command: >
      zkProver -c /usr/src/app/config.json

  zkevm-bridge-service:
    image: hermeznetwork/zkevm-bridge-service:v0.4.0-RC2
    networks:
      - polygon
    deploy:
      placement:
        constraints:
        - node.hostname==hzhx-System-Product-Name
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      - ZKEVM_BRIDGE_DATABASE_USER=test_user
      - ZKEVM_BRIDGE_DATABASE_PASSWORD=test_password
      - ZKEVM_BRIDGE_DATABASE_NAME=test_db
      - ZKEVM_BRIDGE_DATABASE_HOST=bridge1_zkevm-bridge-db
      - ZKEVM_BRIDGE_DATABASE_PORT=5432
    configs:
      - source: test_keystore_claimtx
        target: /pk/keystore.claimtxmanager
      - source: config_local_toml
        target: /app/config.toml
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-bridge run --cfg /app/config.toml"